extends: _base.yaml
name: vlnce_rxr_val_unseen_te
display_name: "VLN-CE RxR Val Unseen (Telugu)"
description: "VLN-CE RxR validation split (unseen environments, Telugu)"
dataset:
  split: "val_unseen_te"
